spring.application.name=Wikilib

# Puerto dinámico para Render
server.port=${PORT:8085}

# MySQL (Aiven)
spring.datasource.url=jdbc:mysql://mysql-2e03ee9a-wikilib.i.aivencloud.com:12883/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_xMZwnU-XGlMFFpbHoPS
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false
